/* tslint:disable */
/* eslint-disable */
/**
 * ChainVue - Verus Multi-Chain Blockchain API
 * REST API for accessing Verus blockchain data across multiple chains. Supports blocks, transactions, addresses, VerusID identities, and multi-currency tracking. All endpoints support chain_id parameter for multi-chain queries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Address } from '../models';
// @ts-ignore
import type { PaginatedApiResponseAddress } from '../models';
// @ts-ignore
import type { Transaction } from '../models';
/**
 * AddressesApi - axios parameter creator
 */
export const AddressesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} address Blockchain address
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddress: async (address: string, chainId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            assertParamExists('getAddress', 'address', address)
            const localVarPath = `/v1/addresses/{address}`
                .replace(`{${"address"}}`, encodeURIComponent(String(address)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} address Blockchain address
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddressBalance: async (address: string, chainId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            assertParamExists('getAddressBalance', 'address', address)
            const localVarPath = `/v1/addresses/{address}/balance`
                .replace(`{${"address"}}`, encodeURIComponent(String(address)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} address Blockchain address
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {boolean} [includeCount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddressTransactions: async (address: string, chainId?: string, limit?: number, offset?: number, includeCount?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            assertParamExists('getAddressTransactions', 'address', address)
            const localVarPath = `/v1/addresses/{address}/transactions`
                .replace(`{${"address"}}`, encodeURIComponent(String(address)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (includeCount !== undefined) {
                localVarQueryParameter['include_count'] = includeCount;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {boolean} [includeCount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRichlist: async (chainId?: string, limit?: number, offset?: number, includeCount?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/addresses/richlist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (includeCount !== undefined) {
                localVarQueryParameter['include_count'] = includeCount;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AddressesApi - functional programming interface
 */
export const AddressesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AddressesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} address Blockchain address
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAddress(address: string, chainId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Address>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAddress(address, chainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AddressesApi.getAddress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} address Blockchain address
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAddressBalance(address: string, chainId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAddressBalance(address, chainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AddressesApi.getAddressBalance']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} address Blockchain address
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {boolean} [includeCount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAddressTransactions(address: string, chainId?: string, limit?: number, offset?: number, includeCount?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Transaction>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAddressTransactions(address, chainId, limit, offset, includeCount, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AddressesApi.getAddressTransactions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {boolean} [includeCount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRichlist(chainId?: string, limit?: number, offset?: number, includeCount?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedApiResponseAddress>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRichlist(chainId, limit, offset, includeCount, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AddressesApi.getRichlist']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AddressesApi - factory interface
 */
export const AddressesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AddressesApiFp(configuration)
    return {
        /**
         * 
         * @param {string} address Blockchain address
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddress(address: string, chainId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Address> {
            return localVarFp.getAddress(address, chainId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} address Blockchain address
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddressBalance(address: string, chainId?: string, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.getAddressBalance(address, chainId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} address Blockchain address
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {boolean} [includeCount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddressTransactions(address: string, chainId?: string, limit?: number, offset?: number, includeCount?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<Array<Transaction>> {
            return localVarFp.getAddressTransactions(address, chainId, limit, offset, includeCount, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {boolean} [includeCount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRichlist(chainId?: string, limit?: number, offset?: number, includeCount?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedApiResponseAddress> {
            return localVarFp.getRichlist(chainId, limit, offset, includeCount, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AddressesApi - object-oriented interface
 */
export class AddressesApi extends BaseAPI {
    /**
     * 
     * @param {string} address Blockchain address
     * @param {string} [chainId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAddress(address: string, chainId?: string, options?: RawAxiosRequestConfig) {
        return AddressesApiFp(this.configuration).getAddress(address, chainId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} address Blockchain address
     * @param {string} [chainId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAddressBalance(address: string, chainId?: string, options?: RawAxiosRequestConfig) {
        return AddressesApiFp(this.configuration).getAddressBalance(address, chainId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} address Blockchain address
     * @param {string} [chainId] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {boolean} [includeCount] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAddressTransactions(address: string, chainId?: string, limit?: number, offset?: number, includeCount?: boolean, options?: RawAxiosRequestConfig) {
        return AddressesApiFp(this.configuration).getAddressTransactions(address, chainId, limit, offset, includeCount, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [chainId] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {boolean} [includeCount] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRichlist(chainId?: string, limit?: number, offset?: number, includeCount?: boolean, options?: RawAxiosRequestConfig) {
        return AddressesApiFp(this.configuration).getRichlist(chainId, limit, offset, includeCount, options).then((request) => request(this.axios, this.basePath));
    }
}

