/* tslint:disable */
/* eslint-disable */
/**
 * ChainVue - Verus Multi-Chain Blockchain API
 * REST API for accessing Verus blockchain data across multiple chains. Supports blocks, transactions, addresses, VerusID identities, and multi-currency tracking. All endpoints support chain_id parameter for multi-chain queries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Block } from '../models';
/**
 * BlocksApi - axios parameter creator
 */
export const BlocksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} heightOrHash Block height (numeric) or block hash
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBlock: async (heightOrHash: string, chainId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'heightOrHash' is not null or undefined
            assertParamExists('getBlock', 'heightOrHash', heightOrHash)
            const localVarPath = `/v1/blocks/{height_or_hash}`
                .replace(`{${"height_or_hash"}}`, encodeURIComponent(String(heightOrHash)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLatestBlock: async (chainId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/blocks/latest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BlocksApi - functional programming interface
 */
export const BlocksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BlocksApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} heightOrHash Block height (numeric) or block hash
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBlock(heightOrHash: string, chainId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Block>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBlock(heightOrHash, chainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlocksApi.getBlock']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLatestBlock(chainId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Block>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLatestBlock(chainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BlocksApi.getLatestBlock']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BlocksApi - factory interface
 */
export const BlocksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BlocksApiFp(configuration)
    return {
        /**
         * 
         * @param {string} heightOrHash Block height (numeric) or block hash
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBlock(heightOrHash: string, chainId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Block> {
            return localVarFp.getBlock(heightOrHash, chainId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLatestBlock(chainId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Block> {
            return localVarFp.getLatestBlock(chainId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BlocksApi - object-oriented interface
 */
export class BlocksApi extends BaseAPI {
    /**
     * 
     * @param {string} heightOrHash Block height (numeric) or block hash
     * @param {string} [chainId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getBlock(heightOrHash: string, chainId?: string, options?: RawAxiosRequestConfig) {
        return BlocksApiFp(this.configuration).getBlock(heightOrHash, chainId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [chainId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLatestBlock(chainId?: string, options?: RawAxiosRequestConfig) {
        return BlocksApiFp(this.configuration).getLatestBlock(chainId, options).then((request) => request(this.axios, this.basePath));
    }
}

