/* tslint:disable */
/* eslint-disable */
/**
 * ChainVue - Verus Multi-Chain Blockchain API
 * REST API for accessing Verus blockchain data across multiple chains. Supports blocks, transactions, addresses, VerusID identities, and multi-currency tracking. All endpoints support chain_id parameter for multi-chain queries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiResponseCurrencyDetail } from '../models';
// @ts-ignore
import type { PaginatedApiResponseCurrency } from '../models';
/**
 * CurrenciesApi - axios parameter creator
 */
export const CurrenciesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve detailed information about a specific currency including all its reserve currencies and weights. Returns the currency definition along with reserve backing information for fractional reserve currencies.
         * @summary Get currency details
         * @param {string} currencyId Unique identifier for the currency (i-address format)
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrency: async (currencyId: string, chainId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'currencyId' is not null or undefined
            assertParamExists('getCurrency', 'currencyId', currencyId)
            const localVarPath = `/v1/currencies/{currency_id}`
                .replace(`{${"currency_id"}}`, encodeURIComponent(String(currencyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve a paginated list of all currencies for a specific chain. Supports optional search filtering by currency name with case-insensitive matching. Results are cached for 60 seconds.
         * @summary List all currencies
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string | null} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCurrencies: async (chainId?: string, limit?: number, offset?: number, search?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/currencies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CurrenciesApi - functional programming interface
 */
export const CurrenciesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CurrenciesApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve detailed information about a specific currency including all its reserve currencies and weights. Returns the currency definition along with reserve backing information for fractional reserve currencies.
         * @summary Get currency details
         * @param {string} currencyId Unique identifier for the currency (i-address format)
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrency(currencyId: string, chainId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiResponseCurrencyDetail>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrency(currencyId, chainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CurrenciesApi.getCurrency']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve a paginated list of all currencies for a specific chain. Supports optional search filtering by currency name with case-insensitive matching. Results are cached for 60 seconds.
         * @summary List all currencies
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string | null} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCurrencies(chainId?: string, limit?: number, offset?: number, search?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedApiResponseCurrency>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCurrencies(chainId, limit, offset, search, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CurrenciesApi.listCurrencies']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CurrenciesApi - factory interface
 */
export const CurrenciesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CurrenciesApiFp(configuration)
    return {
        /**
         * Retrieve detailed information about a specific currency including all its reserve currencies and weights. Returns the currency definition along with reserve backing information for fractional reserve currencies.
         * @summary Get currency details
         * @param {string} currencyId Unique identifier for the currency (i-address format)
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrency(currencyId: string, chainId?: string, options?: RawAxiosRequestConfig): AxiosPromise<ApiResponseCurrencyDetail> {
            return localVarFp.getCurrency(currencyId, chainId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve a paginated list of all currencies for a specific chain. Supports optional search filtering by currency name with case-insensitive matching. Results are cached for 60 seconds.
         * @summary List all currencies
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string | null} [search] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCurrencies(chainId?: string, limit?: number, offset?: number, search?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedApiResponseCurrency> {
            return localVarFp.listCurrencies(chainId, limit, offset, search, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CurrenciesApi - object-oriented interface
 */
export class CurrenciesApi extends BaseAPI {
    /**
     * Retrieve detailed information about a specific currency including all its reserve currencies and weights. Returns the currency definition along with reserve backing information for fractional reserve currencies.
     * @summary Get currency details
     * @param {string} currencyId Unique identifier for the currency (i-address format)
     * @param {string} [chainId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCurrency(currencyId: string, chainId?: string, options?: RawAxiosRequestConfig) {
        return CurrenciesApiFp(this.configuration).getCurrency(currencyId, chainId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve a paginated list of all currencies for a specific chain. Supports optional search filtering by currency name with case-insensitive matching. Results are cached for 60 seconds.
     * @summary List all currencies
     * @param {string} [chainId] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {string | null} [search] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listCurrencies(chainId?: string, limit?: number, offset?: number, search?: string | null, options?: RawAxiosRequestConfig) {
        return CurrenciesApiFp(this.configuration).listCurrencies(chainId, limit, offset, search, options).then((request) => request(this.axios, this.basePath));
    }
}

