/* tslint:disable */
/* eslint-disable */
/**
 * ChainVue - Verus Multi-Chain Blockchain API
 * REST API for accessing Verus blockchain data across multiple chains. Supports blocks, transactions, addresses, VerusID identities, and multi-currency tracking. All endpoints support chain_id parameter for multi-chain queries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DailyVolume } from '../models';
// @ts-ignore
import type { IdentityActivity } from '../models';
// @ts-ignore
import type { NetworkStats } from '../models';
/**
 * StatsApi - axios parameter creator
 */
export const StatsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIdentityCreation: async (chainId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/stats/identity-creation`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNetworkStats: async (chainId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/stats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTxVolume: async (chainId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/stats/tx-volume`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StatsApi - functional programming interface
 */
export const StatsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StatsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIdentityCreation(chainId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<IdentityActivity>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getIdentityCreation(chainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.getIdentityCreation']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNetworkStats(chainId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NetworkStats>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNetworkStats(chainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.getNetworkStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTxVolume(chainId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DailyVolume>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTxVolume(chainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.getTxVolume']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StatsApi - factory interface
 */
export const StatsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StatsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIdentityCreation(chainId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<IdentityActivity>> {
            return localVarFp.getIdentityCreation(chainId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNetworkStats(chainId?: string, options?: RawAxiosRequestConfig): AxiosPromise<NetworkStats> {
            return localVarFp.getNetworkStats(chainId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTxVolume(chainId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<DailyVolume>> {
            return localVarFp.getTxVolume(chainId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StatsApi - object-oriented interface
 */
export class StatsApi extends BaseAPI {
    /**
     * 
     * @param {string} [chainId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getIdentityCreation(chainId?: string, options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).getIdentityCreation(chainId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [chainId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getNetworkStats(chainId?: string, options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).getNetworkStats(chainId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [chainId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTxVolume(chainId?: string, options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).getTxVolume(chainId, options).then((request) => request(this.axios, this.basePath));
    }
}

