/* tslint:disable */
/* eslint-disable */
/**
 * ChainVue - Verus Multi-Chain Blockchain API
 * REST API for accessing Verus blockchain data across multiple chains. Supports blocks, transactions, addresses, VerusID identities, and multi-currency tracking. All endpoints support chain_id parameter for multi-chain queries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ListBlocks200Response } from '../models';
// @ts-ignore
import type { Transaction } from '../models';
/**
 * TransactionsApi - axios parameter creator
 */
export const TransactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMempool: async (chainId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/transactions/mempool`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} txid Transaction ID
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransaction: async (txid: string, chainId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'txid' is not null or undefined
            assertParamExists('getTransaction', 'txid', txid)
            const localVarPath = `/v1/transactions/{txid}`
                .replace(`{${"txid"}}`, encodeURIComponent(String(txid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [sort] 
         * @param {number | null} [minBlockHeight] 
         * @param {number | null} [maxBlockHeight] 
         * @param {number | null} [minTimestamp] 
         * @param {number | null} [maxTimestamp] 
         * @param {string | null} [address] 
         * @param {boolean} [includeCount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTransactions: async (chainId?: string, limit?: number, offset?: number, sort?: string, minBlockHeight?: number | null, maxBlockHeight?: number | null, minTimestamp?: number | null, maxTimestamp?: number | null, address?: string | null, includeCount?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainId !== undefined) {
                localVarQueryParameter['chain_id'] = chainId;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (minBlockHeight !== undefined) {
                localVarQueryParameter['min_block_height'] = minBlockHeight;
            }

            if (maxBlockHeight !== undefined) {
                localVarQueryParameter['max_block_height'] = maxBlockHeight;
            }

            if (minTimestamp !== undefined) {
                localVarQueryParameter['min_timestamp'] = minTimestamp;
            }

            if (maxTimestamp !== undefined) {
                localVarQueryParameter['max_timestamp'] = maxTimestamp;
            }

            if (address !== undefined) {
                localVarQueryParameter['address'] = address;
            }

            if (includeCount !== undefined) {
                localVarQueryParameter['include_count'] = includeCount;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionsApi - functional programming interface
 */
export const TransactionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransactionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMempool(chainId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Transaction>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMempool(chainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.getMempool']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} txid Transaction ID
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTransaction(txid: string, chainId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Transaction>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTransaction(txid, chainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.getTransaction']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [sort] 
         * @param {number | null} [minBlockHeight] 
         * @param {number | null} [maxBlockHeight] 
         * @param {number | null} [minTimestamp] 
         * @param {number | null} [maxTimestamp] 
         * @param {string | null} [address] 
         * @param {boolean} [includeCount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTransactions(chainId?: string, limit?: number, offset?: number, sort?: string, minBlockHeight?: number | null, maxBlockHeight?: number | null, minTimestamp?: number | null, maxTimestamp?: number | null, address?: string | null, includeCount?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListBlocks200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTransactions(chainId, limit, offset, sort, minBlockHeight, maxBlockHeight, minTimestamp, maxTimestamp, address, includeCount, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransactionsApi.listTransactions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TransactionsApi - factory interface
 */
export const TransactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransactionsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMempool(chainId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<Transaction>> {
            return localVarFp.getMempool(chainId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} txid Transaction ID
         * @param {string} [chainId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransaction(txid: string, chainId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Transaction> {
            return localVarFp.getTransaction(txid, chainId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [chainId] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {string} [sort] 
         * @param {number | null} [minBlockHeight] 
         * @param {number | null} [maxBlockHeight] 
         * @param {number | null} [minTimestamp] 
         * @param {number | null} [maxTimestamp] 
         * @param {string | null} [address] 
         * @param {boolean} [includeCount] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTransactions(chainId?: string, limit?: number, offset?: number, sort?: string, minBlockHeight?: number | null, maxBlockHeight?: number | null, minTimestamp?: number | null, maxTimestamp?: number | null, address?: string | null, includeCount?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<ListBlocks200Response> {
            return localVarFp.listTransactions(chainId, limit, offset, sort, minBlockHeight, maxBlockHeight, minTimestamp, maxTimestamp, address, includeCount, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TransactionsApi - object-oriented interface
 */
export class TransactionsApi extends BaseAPI {
    /**
     * 
     * @param {string} [chainId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMempool(chainId?: string, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).getMempool(chainId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} txid Transaction ID
     * @param {string} [chainId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getTransaction(txid: string, chainId?: string, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).getTransaction(txid, chainId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [chainId] 
     * @param {number} [limit] 
     * @param {number} [offset] 
     * @param {string} [sort] 
     * @param {number | null} [minBlockHeight] 
     * @param {number | null} [maxBlockHeight] 
     * @param {number | null} [minTimestamp] 
     * @param {number | null} [maxTimestamp] 
     * @param {string | null} [address] 
     * @param {boolean} [includeCount] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listTransactions(chainId?: string, limit?: number, offset?: number, sort?: string, minBlockHeight?: number | null, maxBlockHeight?: number | null, minTimestamp?: number | null, maxTimestamp?: number | null, address?: string | null, includeCount?: boolean, options?: RawAxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).listTransactions(chainId, limit, offset, sort, minBlockHeight, maxBlockHeight, minTimestamp, maxTimestamp, address, includeCount, options).then((request) => request(this.axios, this.basePath));
    }
}

