/* tslint:disable */
/* eslint-disable */
/**
 * ChainVue - Verus Multi-Chain Blockchain API
 * REST API for accessing Verus blockchain data across multiple chains. Supports blocks, transactions, addresses, VerusID identities, and multi-currency tracking. All endpoints support chain_id parameter for multi-chain queries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ApiResponseCurrencyData {
    'chain_id': string;
    'created_at'?: string | null;
    'created_block'?: number | null;
    'created_txid'?: string | null;
    'currency_id': string;
    'currency_type'?: string | null;
    'initial_supply'?: string | null;
    'is_pbaas_chain'?: boolean | null;
    'is_token'?: boolean | null;
    'launch_system_id'?: string | null;
    'name': string;
    'options': number;
    'parent_currency_id'?: string | null;
    'proof_protocol'?: number | null;
    'raw_data'?: any;
    'version'?: number | null;
}

