/* tslint:disable */
/* eslint-disable */
/**
 * ChainVue - Verus Multi-Chain Blockchain API
 * REST API for accessing Verus blockchain data across multiple chains. Supports blocks, transactions, addresses, VerusID identities, and multi-currency tracking. All endpoints support chain_id parameter for multi-chain queries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Identity {
    'chain_id': string;
    'created_block'?: number | null;
    'identity_address': string;
    'minimum_signatures'?: number | null;
    'name': string;
    'primary_addresses'?: any | null;
    'raw_data'?: any | null;
    'update_count'?: number | null;
}

