/* tslint:disable */
/* eslint-disable */
/**
 * ChainVue - Verus Multi-Chain Blockchain API
 * REST API for accessing Verus blockchain data across multiple chains. Supports blocks, transactions, addresses, VerusID identities, and multi-currency tracking. All endpoints support chain_id parameter for multi-chain queries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ListBlocks200ResponseMetaPagination } from './list-blocks200-response-meta-pagination';

export interface ListBlocks200ResponseMeta {
    'pagination': ListBlocks200ResponseMetaPagination;
    'request_id': string;
    'timestamp': string;
}

