/* tslint:disable */
/* eslint-disable */
/**
 * ChainVue - Verus Multi-Chain Blockchain API
 * REST API for accessing Verus blockchain data across multiple chains. Supports blocks, transactions, addresses, VerusID identities, and multi-currency tracking. All endpoints support chain_id parameter for multi-chain queries.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ListBlocks200ResponseDataInner {
    'bits'?: string | null;
    'chain_id': string;
    'difficulty'?: number | null;
    'extras'?: any;
    'hash': string;
    'height': number;
    'merkleroot'?: string | null;
    'parent_hash': string;
    'size'?: number | null;
    'status'?: string | null;
    'ts': number;
    'tx_count'?: number | null;
    'version'?: number | null;
}

